config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    resources "articles"
    get '/users/check_email', to: 'users#check_email'
    get 'signup', to: 'users#new'
    resources "users", expect: [:index]

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    get 'myArticle', to: 'articles#my'
    resources :categories

    resources "pictures"
#    get 'manage/:id', to: 'categories#index'
#    post 'manage/:id', to: 'categories#create'
#    delete 'manage/:id', to: 'categories#destroy'
#

end

app/views/layouts/_category.html.erb
<!--
    <div class="row">
        <div class="col-sm-3">
             Category 
            <div class="single category">
                <h3 class="side-title">Category</h3>
                <ul class="list-unstyled">
                    <li><a href="" title="">Business <span class="pull-right">13</span></a></li>
                    <li><a href="" title="">Technology <span class="pull-right">13</span></a></li>
                    <li><a href="" title="">Web <span class="pull-right">13</span></a></li>
                    <li><a href="" title="">Ecommerce <span class="pull-right">13</span></a></li>
                    <li><a href="" title="">Wordpress <span class="pull-right">13</span></a></li>
                    <li><a href="" title="">Android <span class="pull-right">13</span></a></li>
                    <li><a href="" title="">IOS <span class="pull-right">13</span></a></li>
                    <li><a href="" title="">Windows <span class="pull-right">13</span></a></li>
                </ul>
           </div>
        </div> 
    </div>
-->
        <div class="col-sm-3">
            <!-- Category -->
            <div class="single category">
                <h3 class="side-title">Category</h3>
                <ul class="list-unstyled">
                  <li><%= link_to "All", articles_path%></li>
                   <% Category.all.each do |c| %>
                    <li><%= link_to c.name, articles_path(:category_id => c.id) %></li>
                    <%end%>
                </ul>
           </div>
        </div> 

app/views/layouts/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom" style="margin-top: 40px">
    <div class="container">
      <p class="navbar-text pull-left">© 2018 - Site Built By Mr. Bentaleb Youssef <span style="font-weight: bold">Supervised By Mr. Ayoub Ait Lahcen</span>
      </p>
      <%= link_to root_path, class: "navbar-btn btn-success btn pull-right" do %>
        <span class="glyphicon glyphicon-home"></span> Acceuil
        <%end%>
    </div>
</div>

app/views/layouts/_message.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>'>

<a href="#" class="close" data-dismiss="alert"></a>

<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

</div>

<% end %>

</div>

</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png'), root_path, class: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav rech" >
        <li><%= link_to "Rechercher annonce", articles_path %> </li>
        <li><%= link_to "Annonces", articles_path %></li>
        <% if current_user and current_user.admin? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrateur<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Utilisateurs", users_path%></li>
              <li><%= link_to "Modifier Categories", categories_path %></li>
            </ul>
          </li>
          <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right rech">
         <% if !logged_in?%>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Se connecter <span class="caret"></span></a>
              <ul class="dropdown-menu">

                <li><%= link_to "Mon compte", login_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Créer compte", signup_path %></li>
              </ul>
            </li>
           <% else %>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="glyphicon glyphicon-user" style="font-size: 1.2em"></span> <span class="caret"></span></a>
              <ul class="dropdown-menu">

                <li><%= link_to "Mes annonces", myArticle_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Réglage", edit_user_path(current_user) %></li>
                <li><%= link_to "Déconnexion", logout_path, method: :delete %></li>
              </ul>
            </li>
        <%end%>

        <button type="button" class="btn btn-success annonce" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-edit"></span> Déposer une annonce</button>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Choisir une categorie</h4>
      </div>
      <div class="modal-body">
        <% Category.all.each do |c| %>
            <div class="row mod">
                <%= link_to c.name, new_article_path(:id => c.id), class: "btn btn-default mod"%>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/nav' %>
   <%= render 'layouts/message' %>
   <div class="row" style="margin-bottom: 40px">


<!-- Modal -->


        <%= yield %>

   </div>


   <%= render 'layouts/footer' %>
  </body>
</html>